site_name: Asia DevOps Conference Singapore 2025
site_description: Singapore DevOps Conference - Level up your DevOps skills with Microsoft Learn challenges
site_author: Michelle Sandford
site_url: https://codess-aus.github.io/SingaporeDevOps/

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: amber
  features:
    - navigation.instant
    - content.code.copy
  font:
    text: Inter
    code: Fira Code

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/michelle-sandford
      name: LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/codess-aus
      name: GitHub
    - icon: fontawesome/brands/mastodon
      link: https://bsky.app/profile/codess-aus.bsky.social
      name: Bluesky
